[package]
name = "lum-s/ui-blur"
description = "Use to generate a blur effect behind GUI Frames"
version = "0.1.1"
license = "Apache-2.0"
authors = ["NikoVonn"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
